import { TOKEN_KINDS } from './tokens.mjs';

const PLACEHOLDER = '_None recorded. Add entries here when a deviation is intentional; audits will stop flagging them._';

const LABELS = {
  color: 'Colour', spacing: 'Spacing', radius: 'Radius',
  type: 'Typography', shadow: 'Shadow', motion: 'Motion', other: 'Other',
};

function tokenTable(tokens) {
  const rows = Object.entries(tokens).map(([name, value]) => `| ${name} | \`${value}\` |`);
  return ['| Token | Value |', '| --- | --- |', ...rows].join('\n');
}

export function renderDesignDoc(profile, exceptions = PLACEHOLDER) {
  const { styling, components, conventions, tokens } = profile;
  const parts = [];

  parts.push('# Design System');
  parts.push('');
  parts.push(`_Generated by ux-engine on ${profile.generatedAt}. Hand edits to this file are authoritative — re-running \`/ux-design-system\` proposes changes rather than overwriting._`);
  parts.push('');

  parts.push('## Tokens');
  parts.push('');
  parts.push(styling.tokenSource.length
    ? `Source: ${styling.tokenSource.map((s) => `\`${s}\``).join(', ')} (${styling.tokenSyntax}).`
    : 'No token source found. Values below were not detected — fill this in by hand.');
  parts.push('');
  for (const kind of TOKEN_KINDS) {
    const group = tokens[kind] ?? {};
    if (!Object.keys(group).length) continue;
    parts.push(`### ${LABELS[kind]}`);
    parts.push('');
    parts.push(tokenTable(group));
    parts.push('');
  }

  parts.push('## Components');
  parts.push('');
  parts.push(`- Directory: ${components.dir ? `\`${components.dir}\`` : '_not detected_'}`);
  parts.push(`- Library: ${components.library ?? '_none_'}`);
  parts.push(`- Variants expressed via: \`${components.variantMechanism}\``);
  parts.push(`- Primitives: ${components.primitives ?? '_none_'}`);
  parts.push('');

  parts.push('## Conventions');
  parts.push('');
  parts.push(`- Styling system: ${styling.system ?? '_not detected_'}${styling.utilityFirst ? ' (utility-first)' : ''}`);
  parts.push(`- Framework: ${conventions.framework ?? '_not detected_'}`);
  parts.push(`- Router: ${conventions.router ?? '_none_'}`);
  parts.push(`- Test runner: ${conventions.testRunner ?? '_not detected_'}`);
  parts.push(`- Icon set: ${conventions.iconSet ?? '_none_'}`);
  parts.push(`- Accessibility target: ${conventions.a11yTarget}`);
  parts.push('');

  parts.push('## Deliberate Exceptions');
  parts.push('');
  parts.push(exceptions.trim());
  parts.push('');

  return parts.join('\n');
}

export function extractExceptions(markdown) {
  const match = /## Deliberate Exceptions\n([\s\S]*?)(?=\n## |$)/.exec(markdown ?? '');
  const body = match?.[1]?.trim();
  return body && body.length ? body : PLACEHOLDER;
}
