import { TOKEN_KINDS } from './tokens.mjs';

// The legend travels with the section so a human editing DESIGN.md learns
// the format without reading the docs. scripts/lib/exceptions.mjs parses
// the same shape; prose lines like these two are ignored by it.
const PLACEHOLDER = [
  'One per line: `<mode-id or *> | <glob> | <reason>`',
  '',
  '_None recorded. Add entries here when a deviation is intentional; audits will stop flagging them._',
].join('\n');

const LABELS = {
  color: 'Colour', spacing: 'Spacing', radius: 'Radius',
  type: 'Typography', shadow: 'Shadow', motion: 'Motion', other: 'Other',
};

function tokenTable(tokens) {
  const rows = Object.entries(tokens).map(([name, value]) => {
    // A hand-transcribed CSS-in-JS token (references/detection.md's
    // documented path for a JS/TS theme object) may be a number, e.g.
    // `{"--s": 4}` — String() coerces before .replace() so that documented
    // happy path renders "4" instead of crashing on a non-string .replace.
    // Collapse internal whitespace to single spaces and escape pipe and backtick.
    const escaped = String(value).replace(/\s+/g, ' ').replace(/\|/g, '\\|').replace(/`/g, '\\`');
    return `| ${name} | \`${escaped}\` |`;
  });
  return ['| Token | Value |', '| --- | --- |', ...rows].join('\n');
}

export function renderDesignDoc(profile, exceptions = PLACEHOLDER, extraSections = '') {
  const { styling, components, conventions, tokens } = profile;
  const parts = [];

  parts.push('# Design System');
  parts.push('');
  parts.push(`_Generated by ux-engine on ${profile.generatedAt}. Hand-written sections are preserved, and generated sections are rebuilt from the project on each run._`);
  parts.push('');

  parts.push('## Tokens');
  parts.push('');
  parts.push(styling.tokenSource.length
    ? `Source: ${styling.tokenSource.map((s) => `\`${s}\``).join(', ')} (${styling.tokenSyntax}).`
    : 'No token source found. Values below were not detected — fill this in by hand.');
  parts.push('');
  for (const kind of TOKEN_KINDS) {
    const group = tokens[kind] ?? {};
    if (!Object.keys(group).length) continue;
    parts.push(`### ${LABELS[kind]}`);
    parts.push('');
    parts.push(tokenTable(group));
    parts.push('');
  }

  parts.push('## Components');
  parts.push('');
  parts.push(`- Directory: ${components.dir ? `\`${components.dir}\`` : '_not detected_'}`);
  parts.push(`- Library: ${components.library ?? '_none_'}`);
  parts.push(`- Variants expressed via: \`${components.variantMechanism}\``);
  parts.push(`- Primitives: ${components.primitives ?? '_none_'}`);
  parts.push('');

  parts.push('## Conventions');
  parts.push('');
  parts.push(`- Styling system: ${styling.system ?? '_not detected_'}${styling.utilityFirst ? ' (utility-first)' : ''}`);
  parts.push(`- Framework: ${conventions.framework ?? '_not detected_'}`);
  parts.push(`- Router: ${conventions.router ?? '_none_'}`);
  parts.push(`- Test runner: ${conventions.testRunner ?? '_not detected_'}`);
  parts.push(`- Icon set: ${conventions.iconSet ?? '_none_'}`);
  parts.push(`- Accessibility target: ${conventions.a11yTarget}`);
  parts.push('');

  parts.push('## Deliberate Exceptions');
  parts.push('');
  parts.push(exceptions.trim());
  parts.push('');

  if (extraSections) {
    parts.push(extraSections);
    parts.push('');
  }

  return parts.join('\n');
}

// Splits markdown into its top-level `## ` sections, in order, ignoring any
// line that falls inside a fenced code block (``` ... ```) so a heading-like
// line inside a fence is never mistaken for a real section boundary.
function splitSections(markdown) {
  const lines = (markdown ?? '').split('\n');
  const sections = [];
  let current = null;
  let inFence = false;

  for (const line of lines) {
    const isFenceToggle = /^\s*```/.test(line);
    if (isFenceToggle) {
      inFence = !inFence;
      if (current) current.bodyLines.push(line);
      continue;
    }
    const headingMatch = !inFence && /^## (.+)$/.exec(line);
    if (headingMatch) {
      if (current) sections.push(current);
      current = { heading: headingMatch[1].trim(), bodyLines: [] };
      continue;
    }
    if (current) current.bodyLines.push(line);
  }
  if (current) sections.push(current);

  return sections.map((s) => ({ heading: s.heading, body: s.bodyLines.join('\n') }));
}

export function extractExceptions(markdown) {
  const section = splitSections(markdown).find((s) => s.heading === 'Deliberate Exceptions');
  const body = section?.body?.trim();
  return body && body.length ? body : PLACEHOLDER;
}

export function extractUnknownSections(markdown) {
  const KNOWN = new Set(['Tokens', 'Components', 'Conventions', 'Deliberate Exceptions']);
  const unknown = splitSections(markdown).filter((s) => !KNOWN.has(s.heading));
  return unknown.map((s) => `## ${s.heading}\n${s.body.trim()}`).join('\n\n');
}
